name: Complete Workflow

on: 
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        poetry-version: ['1.1.11','1.1.13']

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run all tests
        run: poetry run pytest 